create table if not exists public.admins (
  id bigint generated by default as identity primary key,
  user_id uuid unique not null,
  email text,
  role text default 'super_admin',
  is_active boolean default true,
  created_at timestamptz default now()
);

create table if not exists public.app_settings (
  key text primary key,
  value jsonb not null,
  updated_at timestamptz default now()
);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  admin_user_id uuid,
  action text not null,
  target_type text,
  target_id text,
  details jsonb default '{}'::jsonb,
  created_at timestamptz default now()
);

insert into public.app_settings (key, value)
values
('auto_expire_days', '4'::jsonb),
('emergency_alert_min_bags', '2'::jsonb),
('cooldown_days', '90'::jsonb),
('alert_priority_scope', '"upazila_first"'::jsonb)
on conflict (key) do nothing;

alter table public.admins enable row level security;
alter table public.app_settings enable row level security;
alter table public.audit_logs enable row level security;

drop policy if exists admins_select_self on public.admins;
create policy admins_select_self on public.admins
for select to authenticated
using (auth.uid() = user_id);

drop policy if exists app_settings_admin_read on public.app_settings;
create policy app_settings_admin_read on public.app_settings
for select to authenticated
using (exists (select 1 from public.admins a where a.user_id = auth.uid() and a.is_active = true));

drop policy if exists app_settings_admin_write on public.app_settings;
create policy app_settings_admin_write on public.app_settings
for all to authenticated
using (exists (select 1 from public.admins a where a.user_id = auth.uid() and a.is_active = true))
with check (exists (select 1 from public.admins a where a.user_id = auth.uid() and a.is_active = true));

drop policy if exists audit_logs_admin_read on public.audit_logs;
create policy audit_logs_admin_read on public.audit_logs
for select to authenticated
using (exists (select 1 from public.admins a where a.user_id = auth.uid() and a.is_active = true));

drop policy if exists audit_logs_admin_insert on public.audit_logs;
create policy audit_logs_admin_insert on public.audit_logs
for insert to authenticated
with check (exists (select 1 from public.admins a where a.user_id = auth.uid() and a.is_active = true));

drop policy if exists donors_admin_update on public.donors;
create policy donors_admin_update on public.donors
for update to authenticated
using (exists (select 1 from public.admins a where a.user_id = auth.uid() and a.is_active = true))
with check (exists (select 1 from public.admins a where a.user_id = auth.uid() and a.is_active = true));

drop policy if exists blood_requests_admin_update on public.blood_requests;
create policy blood_requests_admin_update on public.blood_requests
for update to authenticated
using (exists (select 1 from public.admins a where a.user_id = auth.uid() and a.is_active = true))
with check (exists (select 1 from public.admins a where a.user_id = auth.uid() and a.is_active = true));

drop policy if exists blood_requests_admin_delete on public.blood_requests;
create policy blood_requests_admin_delete on public.blood_requests
for delete to authenticated
using (exists (select 1 from public.admins a where a.user_id = auth.uid() and a.is_active = true));

drop policy if exists pending_verifications_admin_update on public.pending_verifications;
create policy pending_verifications_admin_update on public.pending_verifications
for update to authenticated
using (exists (select 1 from public.admins a where a.user_id = auth.uid() and a.is_active = true))
with check (exists (select 1 from public.admins a where a.user_id = auth.uid() and a.is_active = true));

drop policy if exists pending_verifications_admin_delete on public.pending_verifications;
create policy pending_verifications_admin_delete on public.pending_verifications
for delete to authenticated
using (exists (select 1 from public.admins a where a.user_id = auth.uid() and a.is_active = true));

drop policy if exists donation_events_admin_insert on public.donation_events;
create policy donation_events_admin_insert on public.donation_events
for insert to authenticated
with check (exists (select 1 from public.admins a where a.user_id = auth.uid() and a.is_active = true));

-- After running this SQL, add yourself as admin manually:
-- insert into public.admins (user_id, email, role, is_active) values ('YOUR_USER_ID', 'your@email.com', 'super_admin', true);
